<a href="https://colab.research.google.com/github/sobiya1234/Python/blob/main/Python_Assignment_6_Array_Operations_using_NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Operations:  

In [ ]:

import numpy as np


In [ ]:
# 1.	Create NumPy Arrays:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)



[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2.	**Inspection and Properties:**

In [ ]:
# Inspect the shape of the temperatures_w1 array.

print(temperatures_w1.shape)

(7,)


In [ ]:
#	Determine the data type of the temperatures_w1 array elements.

print(temperatures_w1.dtype)

float64


In [ ]:
# Find out the number of elements in the temperatures_w1 array.

print(temperatures_w1.size)

7


3.	**Array Operations:**

In [ ]:
# Convert the temperatures_w1 from Celsius to Fahrenheit.

temperatures_fahrenheit = (temperatures_w1 * 9/5) + 32

print(temperatures_fahrenheit)


[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
#	Find the maximum and minimum and average temperatures of the week.

max_temperature = temperatures_w1.max()

min_temperature = temperatures_w1.min()

print("Maximum temperature:", max_temperature)
print("Minimum temperature:", min_temperature)


Maximum temperature: 26.1
Minimum temperature: 20.8


In [ ]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Mean temperatures:",np.mean(temperatures_w1))

Mean temperatures: 23.542857142857144


4.Array Slicing and Indexing:

In [ ]:
#	Extract the temperatures for the first three days of the week.
temperaturess_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("First three days:", temperatures_w1[:3])

First three days: [22.5 25.3 20.8]


In [ ]:
#	Extract the temperatures for the weekend.
temperaturess_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Last two days:", temperatures_w1[-2:])

Last two days: [24.8 21.9]


In [ ]:
# Extract the temperatures for the middle three days of the week.
temperaturess_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Middel three days:", temperatures_w1[2:5:])

Middel three days: [20.8 23.4 26.1]


5.	Create a 2D Array:

In [ ]:
#Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:
week1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
week2 =[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
temperature = np.array([week1,week2])
print("temperature:\n",temperature)

temperature:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6.	Inspect and Slice the 2D Array:

In [ ]:
# Inspect and print the shape, data type, and total number of elements in the temperatures array.
week1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
week2 =[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]

temperatures=np.array([week1,week2])
print("Temperatures of shape:", temperatures.shape)
print("Temperatures of datatypes:", temperatures.dtype)
print("Temperatures of Size:", temperatures.size)

Temperatures of shape: (2, 7)
Temperatures of datatypes: float64
Temperatures of Size: 14


In [ ]:
#	The temperatures for the first week (Row 1).

temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                     [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
week1=temperatures[0]

print("temperatures of first week:",week1)


temperatures of first week: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#	The temperatures for the second week (Row 2).
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                     [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
week2=temperatures[1]

print("temperatures of second week:",week2)



temperatures of second week: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
#	The temperatures for the first three days of each week.
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

first_three_days_each_week = temperatures[:,:3]
print("first three days of week:\n",first_three_days_each_week)

first three days of week:
 [[22.5 25.3 20.8]
 [19.2 22.5 21.3]]


In [ ]:
#	The temperatures for the weekends (last two days) of both weeks.
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

weekend_temperatures = temperatures[:, -2:]
print("Weekend temperatures of last two days:\n", weekend_temperatures)

Weekend temperatures of last two days:
 [[24.8 21.9]
 [22.8 20.1]]
